<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="99" started-at="2018-08-31T10:48:53Z" finished-at="2018-08-31T10:48:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="99" started-at="2018-08-31T10:48:53Z" finished-at="2018-08-31T10:48:53Z">
      <class name="demo.pack.DemoProject2.DemoClass">
        <test-method status="PASS" signature="orange()[pri:0, instance:demo.pack.DemoProject2.DemoClass@23d2a7e8]" name="orange" duration-ms="16" started-at="2018-08-31T10:48:53Z" finished-at="2018-08-31T10:48:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orange -->
        <test-method status="PASS" signature="white()[pri:0, instance:demo.pack.DemoProject2.DemoClass@23d2a7e8]" name="white" duration-ms="0" started-at="2018-08-31T10:48:53Z" depends-on-methods="demo.pack.DemoProject2.DemoClass.orange" finished-at="2018-08-31T10:48:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- white -->
        <test-method status="FAIL" signature="black()[pri:0, instance:demo.pack.DemoProject2.DemoClass@23d2a7e8]" name="black" duration-ms="0" started-at="2018-08-31T10:48:53Z" depends-on-methods="demo.pack.DemoProject2.DemoClass.white" finished-at="2018-08-31T10:48:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at demo.pack.DemoProject2.DemoClass.black(DemoClass.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- black -->
        <test-method status="SKIP" signature="green()[pri:0, instance:demo.pack.DemoProject2.DemoClass@23d2a7e8]" name="green" duration-ms="0" started-at="2018-08-31T10:48:53Z" depends-on-methods="demo.pack.DemoProject2.DemoClass.black" finished-at="2018-08-31T10:48:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DemoClass.green()[pri:0, instance:demo.pack.DemoProject2.DemoClass@23d2a7e8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DemoClass.green()[pri:0, instance:demo.pack.DemoProject2.DemoClass@23d2a7e8] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- green -->
      </class> <!-- demo.pack.DemoProject2.DemoClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
